version: 0.2

phases:
  install:
    commands:
      - echo Install started on `date`
      - composer install
      - cp .env.example .env
      - php artisan key:gen
  build:
    commands:
      - echo Build started on `date`
      - vendor/bin/phpunit
  post_build:
    commands:
      - echo Test completed on `date`
